import React from 'react';
import { Link } from 'react-router-dom';
import {
  Sparkles, Upload, Wand2, Download, Shield, Zap,
  Palette, Camera, ChevronRight, Star,
} from 'lucide-react';
const FEATURES = [
  { icon: Camera,  title: 'Smart Pose Detection',   desc: 'MediaPipe AI detects 33 body keypoints for perfect saree alignment.'       },
  { icon: Wand2,   title: 'AI Draping Engine',      desc: 'Geometric transformations generate realistic pleats, pallu & body wrap.'    },
  { icon: Palette, title: 'Blouse Customization',   desc: 'Round, boat, V-neck, short/half/full sleeves with custom color matching.'   },
  { icon: Shield,  title: 'Privacy First',          desc: 'Temporary images are automatically deleted after download.'                  },
  { icon: Zap,     title: 'Real-time Preview',      desc: 'See your saree draped in seconds with our fast rendering pipeline.'         },
  { icon: Star,    title: 'Multiple Draping Styles', desc: 'Nivi, Bridal, Hanging, Gujarati — all authentic regional styles.'          },
];

const STYLES = [
  { name: 'Nivi Style',     region: 'South India', color: 'from-purple-600 to-pink-500'  },
  { name: 'Bridal Style',   region: 'Pan India',   color: 'from-rose-600   to-orange-500'},
  { name: 'Hanging Style',  region: 'East India',  color: 'from-blue-600   to-cyan-500'  },
  { name: 'Gujarati Style', region: 'West India',  color: 'from-amber-500  to-yellow-400'},
];

const STEPS = [
  { n: '01', title: 'Upload Body Image',   desc: 'Upload a clear full-body photo for accurate pose detection.' },
  { n: '02', title: 'Choose Saree',        desc: 'Upload your saree fabric or pick from our template library.' },
  { n: '03', title: 'Customize Blouse',    desc: 'Select neck style, sleeve length, and colour.'               },
  { n: '04', title: 'Generate & Download', desc: 'AI renders the final draped image. Download in HD.'           },
];

export default function HomePage() {
  return (
    <div className="min-h-screen">
      {/* ── Hero ─────────────────────────────────────────────────────────────── */}
      <section className="relative overflow-hidden">
        {/* Background gradient orbs */}
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-20 left-1/4 w-96 h-96 bg-saree-600/20 rounded-full blur-3xl" />
          <div className="absolute bottom-20 right-1/4 w-80 h-80 bg-saree-400/10 rounded-full blur-3xl" />
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 text-center">
          <div className="inline-flex items-center gap-2 bg-saree-500/10 border border-saree-500/20 text-saree-300 px-4 py-2 rounded-full text-sm font-medium mb-8">
            <Sparkles className="w-4 h-4" />
            AI-Powered Virtual Saree Draping
          </div>
          <h1 className="font-display text-5xl sm:text-7xl font-bold text-white leading-tight mb-6">
            Drape Your{' '}
            <span className="bg-gradient-to-r from-saree-400 to-pink-400 bg-clip-text text-transparent">
              Perfect Saree
            </span>
          </h1>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-10 leading-relaxed">
            Upload your photo and saree fabric — our AI engine precisely drapes the saree
            on your body with realistic pleats, pallu, and custom blouse in seconds.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              to="/upload"
              className="btn-primary flex items-center gap-2 text-base !px-8 !py-4"
            >
              <Wand2 className="w-5 h-5" />
              Start Draping
              <ChevronRight className="w-4 h-4" />
            </Link>
          </div>

          {/* Stats */}
          <div className="mt-16 grid grid-cols-3 gap-8 max-w-lg mx-auto">
            {[['4+', 'Draping Styles'], ['5+', 'Fabric Types'], ['100%', 'AI Powered']].map(([num, label]) => (
              <div key={label} className="text-center">
                <div className="text-3xl font-display font-bold text-saree-400">{num}</div>
                <div className="text-xs text-gray-500 mt-1">{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Draping Styles ───────────────────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="font-display text-4xl font-bold text-white text-center mb-4">
          Draping Styles
        </h2>
        <p className="text-gray-400 text-center mb-12">Authentic regional styles generated by our AI engine</p>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {STYLES.map(s => (
            <div key={s.name} className="card p-6 text-center hover:-translate-y-1 transition-transform duration-300">
              <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${s.color} mx-auto mb-4 flex items-center justify-center shadow-lg`}>
                <Sparkles className="w-7 h-7 text-white" />
              </div>
              <h3 className="font-semibold text-white mb-1">{s.name}</h3>
              <p className="text-xs text-gray-400">{s.region}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── How It Works ─────────────────────────────────────────────────────── */}
      <section className="bg-gray-900/40 border-y border-white/5 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="font-display text-4xl font-bold text-white text-center mb-4">
            How It Works
          </h2>
          <p className="text-gray-400 text-center mb-12">Four simple steps to your perfect drape</p>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            {STEPS.map((step, idx) => (
              <div key={step.n} className="relative">
                {idx < STEPS.length - 1 && (
                  <div className="hidden md:block absolute top-6 left-[calc(50%+2rem)] w-[calc(100%-4rem)] h-0.5 bg-saree-500/20" />
                )}
                <div className="card p-6 text-center">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-saree-600 to-saree-400 flex items-center justify-center text-white font-bold text-lg mx-auto mb-4 shadow-lg shadow-saree-500/30">
                    {step.n}
                  </div>
                  <h3 className="font-semibold text-white mb-2">{step.title}</h3>
                  <p className="text-xs text-gray-400 leading-relaxed">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ─────────────────────────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="font-display text-4xl font-bold text-white text-center mb-4">
          Powered by Modern AI
        </h2>
        <p className="text-gray-400 text-center mb-12">Everything you need for a perfect virtual try-on</p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map(f => (
            <div key={f.title} className="card p-6 hover:border-saree-500/30 transition-colors duration-300">
              <div className="w-12 h-12 rounded-xl bg-saree-500/10 border border-saree-500/20 flex items-center justify-center mb-4">
                <f.icon className="w-6 h-6 text-saree-400" />
              </div>
              <h3 className="font-semibold text-white mb-2">{f.title}</h3>
              <p className="text-sm text-gray-400 leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="relative overflow-hidden card p-12 text-center">
          <div className="absolute inset-0 bg-gradient-to-br from-saree-900/40 to-gray-900/40 pointer-events-none" />
          <div className="relative">
            <h2 className="font-display text-4xl font-bold text-white mb-4">
              Ready to Drape?
            </h2>
            <p className="text-gray-400 mb-8 max-w-md mx-auto">
              Join thousands of users who have discovered the perfect saree draping with AI.
            </p>
            <Link
              to="/upload"
              className="btn-primary inline-flex items-center gap-2 text-base !px-10 !py-4"
            >
              <Upload className="w-5 h-5" />
              Start Draping Now
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8 text-center text-gray-500 text-sm">
        <p>© 2024 SareeDrape Studio. Built with React, Flask & MediaPipe AI.</p>
      </footer>
    </div>
  );
}
